<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7LIfrgT\Combodo_iTop_Portal_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7LIfrgT/Combodo_iTop_Portal_KernelProdContainer.php') {
    touch(__DIR__.'/Container7LIfrgT.legacy');

    return;
}

if (!\class_exists(Combodo_iTop_Portal_KernelProdContainer::class, false)) {
    \class_alias(\Container7LIfrgT\Combodo_iTop_Portal_KernelProdContainer::class, Combodo_iTop_Portal_KernelProdContainer::class, false);
}

return new \Container7LIfrgT\Combodo_iTop_Portal_KernelProdContainer([
    'container.build_hash' => '7LIfrgT',
    'container.build_id' => '2a3d7bf2',
    'container.build_time' => 1745480784,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7LIfrgT');
