<?php

namespace Container7LIfrgT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCombodo_CurrentUserService extends Combodo_iTop_Portal_KernelProdContainer
{
    /*
     * Gets the public 'combodo.current_user' shared autowired service.
     *
     * @return \Combodo\iTop\Portal\Twig\CurrentUserAccessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'env-production'.\DIRECTORY_SEPARATOR.'itop-portal-base'.\DIRECTORY_SEPARATOR.'portal'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'CurrentUserAccessor.php';

        return $container->services['combodo.current_user'] = new \Combodo\iTop\Portal\Twig\CurrentUserAccessor(($container->privates['Combodo\\iTop\\Portal\\EventListener\\UserProvider'] ?? $container->getUserProviderService()));
    }
}
