<?php

namespace Container7LIfrgT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getObjectFormHandlerService extends Combodo_iTop_Portal_KernelProdContainer
{
    /*
     * Gets the public 'object_form_handler' shared autowired service.
     *
     * @return \Combodo\iTop\Portal\Helper\ObjectFormHandlerHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'env-production'.\DIRECTORY_SEPARATOR.'itop-portal-base'.\DIRECTORY_SEPARATOR.'portal'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Helper'.\DIRECTORY_SEPARATOR.'ObjectFormHandlerHelper.php';
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'twig'.\DIRECTORY_SEPARATOR.'twig'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'ExtensionInterface.php';
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'twig'.\DIRECTORY_SEPARATOR.'twig'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'AbstractExtension.php';
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'env-production'.\DIRECTORY_SEPARATOR.'itop-portal-base'.\DIRECTORY_SEPARATOR.'portal'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'AppExtension.php';

        return $container->services['object_form_handler'] = new \Combodo\iTop\Portal\Helper\ObjectFormHandlerHelper(($container->services['request_manipulator'] ?? $container->load('getRequestManipulatorService')), ($container->services['context_manipulator'] ?? $container->load('getContextManipulatorService')), ($container->services['navigation_rule_helper'] ?? $container->load('getNavigationRuleHelperService')), ($container->services['scope_validator'] ?? $container->load('getScopeValidatorService')), ($container->services['security_helper'] ?? $container->load('getSecurityHelperService')), ($container->services['url_generator'] ?? $container->getUrlGeneratorService()), $container->parameters['combodo.portal.instance.conf'], $container->getEnv('string:PORTAL_ID'), ($container->privates['Combodo\\iTop\\Portal\\Twig\\AppExtension'] ?? ($container->privates['Combodo\\iTop\\Portal\\Twig\\AppExtension'] = new \Combodo\iTop\Portal\Twig\AppExtension())));
    }
}
