<?php

namespace Container7LIfrgT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityHelperService extends Combodo_iTop_Portal_KernelProdContainer
{
    /*
     * Gets the public 'security_helper' shared autowired service.
     *
     * @return \Combodo\iTop\Portal\Helper\SecurityHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'env-production'.\DIRECTORY_SEPARATOR.'itop-portal-base'.\DIRECTORY_SEPARATOR.'portal'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Helper'.\DIRECTORY_SEPARATOR.'SecurityHelper.php';

        return $container->services['security_helper'] = new \Combodo\iTop\Portal\Helper\SecurityHelper(($container->services['scope_validator'] ?? $container->load('getScopeValidatorService')), ($container->services['lifecycle_validator'] ?? $container->load('getLifecycleValidatorService')), false);
    }
}
