<?php

namespace Container7LIfrgT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUiExtensionsHelperService extends Combodo_iTop_Portal_KernelProdContainer
{
    /*
     * Gets the public 'ui_extensions_helper' shared autowired service.
     *
     * @return \Combodo\iTop\Portal\Helper\UIExtensionsHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'env-production'.\DIRECTORY_SEPARATOR.'itop-portal-base'.\DIRECTORY_SEPARATOR.'portal'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Helper'.\DIRECTORY_SEPARATOR.'UIExtensionsHelper.php';

        return $container->services['ui_extensions_helper'] = new \Combodo\iTop\Portal\Helper\UIExtensionsHelper($container);
    }
}
